/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:123efe10-05f0-4f99-a3a9-42405054d0c8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8BHVDE0eh",
    "aws_user_pools_web_client_id": "40nt49pdba9gij54kjmacpdrc7",
    "oauth": {}
};


export default awsmobile;
